# Generated by Django 4.2.4 on 2023-08-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_form_date_alter_form_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
